import os
import re
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(__file__))
from questionnaire_map import (
    BLOCK_MAP,
    FREE_TEXT_COLS,
    MULTI_CHOICE_COLS,
    QUESTION_MAP,
    VALID_RESPONSES,
)

ID_COLS = ["Qmun", "Qnome_unidade", "Qcount_criancas"]


def _extract_number(val) -> int:
    if pd.isna(val):
        return 0
    nums = re.findall(r"\d+", str(val))
    return int(nums[0]) if nums else 0


def _clean_response(val) -> str:
    if pd.isna(val):
        return "Não Informado"
    s = str(val).strip()
    if s in ("-", "", "nan", "None"):
        return "Não Informado"
    return s


def _get_block(col_id: str) -> str:
    return col_id[0].upper()


def load_and_deduplicate(filepath: str) -> pd.DataFrame:
    """
    Read Excel, resolve duplicate rows generated by multiple-choice columns
    (C12_Tipo and F04_Tipo). Each option selected by a unit creates an extra
    row; we collapse them by joining the distinct values per unit.
    """
    df = pd.read_excel(filepath)

    question_cols = [c for c in df.columns if c not in ID_COLS]

    agg: dict = {"Qcount_criancas": "first"}
    for col in question_cols:
        if col in MULTI_CHOICE_COLS:
            agg[col] = lambda x: " | ".join(
                sorted(x.dropna().astype(str).unique())
            )
        else:
            agg[col] = "first"

    df_dedup = df.groupby(
        ["Qmun", "Qnome_unidade"], sort=False, as_index=False
    ).agg(agg)

    return df_dedup


def pivot_to_long(df: pd.DataFrame) -> pd.DataFrame:
    """Pivot wide → long; add question text, block, and response flags."""
    df = df.copy()
    df["Qcount_criancas_num"] = df["Qcount_criancas"].apply(_extract_number)

    analysis_cols = [
        c for c in df.columns
        if c in QUESTION_MAP and c not in FREE_TEXT_COLS
    ]

    base_cols = ["Qmun", "Qnome_unidade", "Qcount_criancas_num"]
    df_long = df[base_cols + analysis_cols].melt(
        id_vars=base_cols,
        var_name="ID_Pergunta",
        value_name="_raw",
    )

    df_long["Resposta"] = df_long["_raw"].apply(_clean_response)
    df_long["Texto_Pergunta"] = df_long["ID_Pergunta"].map(QUESTION_MAP)
    df_long["Bloco_ID"] = df_long["ID_Pergunta"].apply(_get_block)
    df_long["Bloco_Nome"] = df_long["Bloco_ID"].map(BLOCK_MAP)
    df_long["Resposta_Valida"] = df_long["Resposta"].isin(VALID_RESPONSES)

    return df_long.drop(columns=["_raw"])


def run_etl() -> None:
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    input_path = os.path.join(base_dir, "archives", "CxVqt.xlsx")
    output_dir = os.path.join(base_dir, "data")
    os.makedirs(output_dir, exist_ok=True)

    print("Carregando e desduplicando dados...")
    df = load_and_deduplicate(input_path)
    print(f"  {len(df)} unidades únicas após deduplicação")

    print("Pivotando para formato longo...")
    df_long = pivot_to_long(df)
    print(f"  {len(df_long)} registros no formato longo")

    long_path = os.path.join(output_dir, "fact_long.csv")
    df_long.to_csv(long_path, index=False, encoding="utf-8-sig")
    print(f"  Salvo: {long_path}")

    wide_path = os.path.join(output_dir, "fact_wide.csv")
    df.to_csv(wide_path, index=False, encoding="utf-8-sig")
    print(f"  Salvo: {wide_path}")


if __name__ == "__main__":
    run_etl()
