[server]
headless = true
enableCORS = false

[theme]
base = "light"
primaryColor = "#1a559a"
backgroundColor = "#74B2E2"
secondaryBackgroundColor = "#ffffffff"
textColor = "#1a1a1a"
font = "sans serif"
